### ISSUE TITLE
Async execute doesn't get triggered

### ISSUE THREAD

**Issue by deepio** [encode/databases#182] opened 2020-03-29 17:56 UTC
I know this is probably because of the async lock:
- https://github.com/encode/databases/issues/81
- https://github.com/encode/databases/issues/93
- https://github.com/encode/databases/issues/176

But because this seems to be a fairly big (common) issue I really think it should have complete examples or more documentation. I got the same results in both sqlite and postgres and I can't seem to progress any further. 

```python
import asyncio
from dask.distributed import Client
from databases import Database
import sqlalchemy


def main(id):
  return f"Finished: {id}"


if __name__ == "__main__":
  metadata = sqlalchemy.MetaData()
  filenames = sqlalchemy.Table(  # noqa
    "filenames",
    metadata,
    sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True),
    sqlalchemy.Column("filepath", sqlalchemy.String(length=250)),
    sqlalchemy.Column("completed", sqlalchemy.Boolean),
  )

  async def run_task():
    ip_address = "192.168.2.13:8786"
    async with Client(ip_address, asynchronous=True) as client:

      # async with Database("sqlite:///test.db") as database:
      async with Database("postgresql://postgres:example@localhost:5432") as database:

        query = filenames.select(filenames.c.completed == False)  # noqa
        async for row in database.iterate(query=query):

          # result = await client.submit(main, row.id, pure=False)
          result = await client.submit(main, row.get("id"), pure=False)
          # update_query = filenames.update().where(filenames.c.id == row.id).values(completed=True)
          update_query = filenames.update().where(filenames.c.id == row.get("id")).values(completed=True)
          await database.execute(query=update_query)

  asyncio.run(run_task())
```

How do you get around the connection lock so that I can update the database?

**Comment by deepio** [comment] 2020-03-29 18:10
I think this would work, but I would appreciate some comments/suggestions:
```python
import asyncio
from dask.distributed import Client
from databases import Database
import sqlalchemy


def main(id):
  return f"Finished: {id}"


async def fetch_todo():
  async with Database("postgresql://postgres:example@localhost:5432") as database:
    query = filenames.select(filenames.c.completed == False)  # noqa
    rows = await database.fetch_all(query=query)
  return len(rows)


async def fetch_single():
  async with Database("postgresql://postgres:example@localhost:5432") as database:
    query = filenames.select(filenames.c.completed == False)  # noqa
    row = await database.fetch_one(query=query)
  return row


async def update(id):
  async with Database("postgresql://postgres:example@localhost:5432") as database:
    update_query = filenames.update().where(filenames.c.id == id).values(completed=True)
    res = await database.execute(query=update_query)
  return res


if __name__ == "__main__":
  metadata = sqlalchemy.MetaData()
  filenames = sqlalchemy.Table(  # noqa
    "filenames",
    metadata,
    sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True),
    sqlalchemy.Column("filepath", sqlalchemy.String(length=250)),
    sqlalchemy.Column("completed", sqlalchemy.Boolean),
  )

  async def run_task():
    ip_address = "192.168.2.13:8786"
    async with Client(ip_address, asynchronous=True) as client:

      for _ in range(await fetch_todo()):
        current_page = await fetch_single()
        result = await client.submit(main, current_page.get("id"), pure=False)
        print(result)
        await update(current_page.get("id"))

  asyncio.run(run_task())

```

**Comment by tomchristie** [comment] 2020-03-30 10:00
Closing this as a duplicate of #176.

For now *don't* use `iterate` if you also want to perform DB operations within the loop.

**Closed by tomchristie** 2020-03-30 10:00 UTC
