### ISSUE TITLE
asyncpg.exceptions._base.InterfaceError: Pool.release() received invalid connection: <PoolConnectionProxy <asyncpg.connection.Connection object at 0x7f9f9cc71040> 0x7f9f9cc53070> is not a member of this pool

### ISSUE THREAD

**Issue by shahriyardx** [encode/databases#430] opened 2021-11-28 21:37 UTC
Error : 
```txt
Traceback (most recent call last):
  File "/home/shahriyardx/Projects/customwebsite/customcommands/venv/lib/python3.8/site-packages/quart/app.py", line 1489, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/shahriyardx/Projects/customwebsite/customcommands/venv/lib/python3.8/site-packages/quart/app.py", line 1514, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/shahriyardx/Projects/customwebsite/customcommands/venv/lib/python3.8/site-packages/quart/app.py", line 964, in handle_user_exception
    raise error
  File "/home/shahriyardx/Projects/customwebsite/customcommands/venv/lib/python3.8/site-packages/quart/app.py", line 1512, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/shahriyardx/Projects/customwebsite/customcommands/venv/lib/python3.8/site-packages/quart/app.py", line 1557, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/home/shahriyardx/Projects/customwebsite/customcommands/venv/lib/python3.8/site-packages/quart_discord/utils.py", line 49, in wrapper
    return await view(*args, **kwargs)
  File "/home/shahriyardx/Projects/customwebsite/customcommands/customcommands/apps/backend/views.py", line 25, in dashboard
    premium = await current_app.db.fetch_one(
  File "/home/shahriyardx/Projects/customwebsite/customcommands/customcommands/db.py", line 7, in fetch_one
    data = await con.fetch_one(query=query, values=values)
  File "/home/shahriyardx/Projects/customwebsite/customcommands/venv/lib/python3.8/site-packages/databases/core.py", line 154, in fetch_one
    return await connection.fetch_one(query, values)
  File "/home/shahriyardx/Projects/customwebsite/customcommands/venv/lib/python3.8/site-packages/databases/core.py", line 264, in __aexit__
    await self._connection.release()
  File "/home/shahriyardx/Projects/customwebsite/customcommands/venv/lib/python3.8/site-packages/databases/backends/postgres.py", line 168, in release
    self._connection = await self._database._pool.release(self._connection)
  File "/home/shahriyardx/Projects/customwebsite/customcommands/venv/lib/python3.8/site-packages/asyncpg/pool.py", line 846, in release
    raise exceptions.InterfaceError(
asyncpg.exceptions._base.InterfaceError: Pool.release() received invalid connection: <PoolConnectionProxy <asyncpg.connection.Connection object at 0x7f9f9cc71040> 0x7f9f9cc53070> is not a member of this pool
```

This error happens when I try to execute queries too fast like if a webpage is doing some query execution or fetch then reloading the page too fast raising this error. 

I am doing queries like this

```py
async with database as con:
    await con.whatever(query, values)
```

**Comment by aminalaee** [comment] 2021-11-29 08:09
Thanks for reporting this.

Can you provide a minimal example to reproduce this?

**Comment by shahriyardx** [comment] 2021-11-29 11:11
```py
import asyncio
from databases import Database
from aioscheduler import TimedScheduler # pip install aioscheduler
import datetime

database = Database("postgresql://user:pass@localhost:5432/database")

async def main():
    async with database as con:
        data = await con.fetch_one("SELECT * FROM table")
        print(data)

async def task():
    # aioscheduler is a lib that can be used to schedule job to execute in future.
    scheduler = TimedScheduler(prefer_utc=False)
    scheduler.start()
    
    call_at = datetime.datetime.now() + datetime.timedelta(seconds=10)
    
    # Makes 10 job which will execute at the call_at time all at once
    for _ in range(10):
        scheduler.schedule(main(), call_at)
    
    print("Started 10 jobs starting in 10 seconds")
        
loop = asyncio.get_event_loop()
loop.run_until_complete(task())
loop.run_forever()
```

In this code only the first one succeeded and the other 9 queries which happened at the same time failed.

**Comment by shahriyardx** [comment] 2021-11-29 11:28
This example using asyncpg and it gets succeded without any error

```py
import asyncio
from asyncpg import create_pool
from aioscheduler import TimedScheduler # pip install aioscheduler
import datetime

database = None

async def main():
    async with database.acquire() as con:
        data = await con.fetchrow("SELECT * FROM table")
        print(data)

async def task():
    global database
    database = await create_pool("postgresql://user:pass@localhost:5432/database")
    scheduler = TimedScheduler(prefer_utc=False)
    scheduler.start()
    
    call_at = datetime.datetime.now() + datetime.timedelta(seconds=10)
    
    for _ in range(10):
        scheduler.schedule(main(), call_at)
    
    print("Started 10 jobs starting in 10 seconds")
        
loop = asyncio.get_event_loop()
loop.run_until_complete(task())
loop.run_forever()```

**Comment by aminalaee** [comment] 2021-11-29 13:12
Just a question, why do you need to connect in each task?

I mean can you try something like this?

```python
...
database = Database("postgresql://user:pass@localhost:5432/database")

async def main(db):
    data = await db.fetch_one("SELECT 1")
    print(data)

async def task():
    # aioscheduler is a lib that can be used to schedule job to execute in future.
    scheduler = TimedScheduler(prefer_utc=False)
    scheduler.start()
    
    call_at = datetime.datetime.now() + datetime.timedelta(seconds=10)

   await database.connect()
    
    # Makes 10 job which will execute at the call_at time all at once
    for _ in range(10):
        scheduler.schedule(main(database), call_at)
 
...
```

**Comment by shahriyardx** [comment] 2021-11-29 13:37
So `async with Database as con` is not similar to `sync with database.acquire() as con` in asyncpg? I thought it was the same.

**Comment by aminalaee** [comment] 2021-11-29 14:56
I think `database.acquire()` will give you a connection each time you call that, so it's ok to be called multiple times.
If you want to get a connection per task maybe something like this:


```python
...
database = Database("postgresql://user:pass@localhost:5432/database")

async def main():
    async with database.connection() as conn:
        data = await conn.fetch_one("SELECT 1")
        print(dict(data))

async def task():
    # aioscheduler is a lib that can be used to schedule job to execute in future.
    scheduler = TimedScheduler(prefer_utc=False)
    scheduler.start()
    
    call_at = datetime.datetime.now() + datetime.timedelta(seconds=10)

   await database.connect(). # Calling connect once
    
    # Makes 10 job which will execute at the call_at time all at once
    for _ in range(10):
        scheduler.schedule(main(), call_at)
...
```

**Comment by aminalaee** [comment] 2021-11-29 17:38
I assume the issue is resolved. I'll close this but feel free to update this.

**Closed by aminalaee** 2021-11-29 17:38 UTC
