### ISSUE TITLE
Specifying PostgreSQL specific options

### ISSUE THREAD

**Issue by hyperknot** [encode/databases#91] opened 2019-04-22 23:47 UTC
I'm using the following code in pure SQLAlchemy environment to set up a database to a PG server:

```
from sqlalchemy import create_engine

pg_url = f'postgresql+psycopg2://app:{pg_config["password"]}@{pg_config["host"]}/app'
pg_certs = {
    'sslcert': f'{config_dir}/client-cert.pem',
    'sslkey': f'{config_dir}/client-key.pem',
    'sslrootcert': f'{config_dir}/server-ca.pem',
}

pg_engine = create_engine(
    pg_url,
    connect_args=pg_certs,
    use_batch_mode=True,
    pool_pre_ping=True,
    echo=bool(os.environ.get('SHOWSQL')),
    pool_reset_on_return='rollback',
)
```

How can I put this in a syntax which this package understands?

**Comment by hyperknot** [comment] 2019-04-23 00:26
I figured out how to do the certificates. This is required for Google Cloud SQL SSL pinning mode for example:

```
import ssl

ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
ctx.verify_mode = ssl.CERT_REQUIRED
ctx.load_cert_chain(certfile=..., keyfile=...)
ctx.load_verify_locations(cafile=...)

database = Database(pg_url, ssl=ctx)
```

The other options I guess do not exist? How would you do an echo or a reconnect after loosing connection?

**Comment by tomchristie** [comment] 2019-06-20 09:39
I guess this is essentially a duplicate of #69 right?

We ought to support whatever additional arguments the underlying driver provides, eg. https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.connection.connect

I'll close this off in favor of #69, but happy to reopen if I've missed something and it's not the same.

**Closed by tomchristie** 2019-06-20 09:39 UTC
