### ISSUE TITLE
Raised dialect-specific exception instead of generic ones

### ISSUE THREAD

**Issue by Pedrozena** [encode/databases#325] opened 2021-04-24 13:50 UTC
Hi.
I'm writing a very basic CRUD api server.
I'm noticing that exceptions raised by `database.execute` are dialect-specific:
```python
@database.transaction()
async def db_store_user(user: User):
    query = users.insert().values(**user.dict(exclude_none=True))
    try:
        await database.execute(query)
    except sqlalchemy.exc.IntegrityError:
        raise ValueError("User alredy present")
    except sqlalchemy.exc.SQLAlchemyError:
        raise ValueError("User alredy present")
    except Exception as e:
        print(type(e))

--> <class 'sqlite3.IntegrityError'>
```
Am I doing something wrong? Is there a way to catch the more generic `IntegrityError`?
Thanks for the support.

**Comment by kiarash96** [comment] 2021-11-21 17:31
As of writing this comment I think this is the expected behavior. SQLAlchemy has a whole exception translation layer built into it that catches the dialect-specific errors and maps them to the generic ones. This translation layer is simply missing here. It would be nice if the project authors could clarify whether this is the intended final behavior or if there is room to implement such functionality in this library.

**Comment by aminalaee** [comment] 2021-11-21 18:12
Yes, as you explained there's no mapping for diaelect-specific exceptions into generic ones.
I haven't actually checked it out, but I think it would be a good idea, if we can implement it in a nice way.

Any PR is also welcome. Maybe we can start off by a single dialect and see how it goes.

**Comment by aminalaee** [comment] 2021-11-24 15:09
I'll close this for now, unless someone wants to pick this up.

**Closed by aminalaee** 2021-11-24 15:09 UTC
