### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by euri10** [encode/databases#117] opened 2019-07-01 10:21 UTC
I have a big performance issue, 1.5s using the raw query, more than 16s using the sqlalchemy core version of it.

```
    raw_query = str(stmt.compile(dialect=postgresql.dialect(),  compile_kwargs={"literal_binds": True}))

    conn = await asyncpg.connect(str(databaselake.url))
    direct0 = time.time()
    direct_result = await conn.fetch(raw_query)

    await conn.close()
    direct1 = time.time()
    print(f"direct: {direct1-direct0}")

    raw0 = time.time()
    raw_result = await databaselake.fetch_all(raw_query)
    raw1 = time.time()
    print(f"raw: {raw1-raw0}")

    stmt0 = time.time()
    result = await databaselake.fetch_all(stmt)
    stmt1 = time.time()
    print(f"stmt: {stmt1 - stmt0}")
    print("result ok")
```

direct: 1.3257312774658203
raw: 1.4148566722869873
stmt1: 19.825509071350098

`direct` and `raw` both use `raw_query` which is the fully compiled version of `stmt` 

They have similar performance, in line with what I get from entering the query in psql, around 1.5s

`direct` uses asyncpg directly, this was just to test, while `raw` uses databases

now the fetch_all version using the sqlachemy core `stmt` takes 16 times more time...

the query returns about 21 columns and 4500 rows. it's about 80 000 characters long, not sure it makes sense to paste it here but maybe there's something else I havn't considered

edit: the raw statement looks like this

```
select l.field1, l.field2, l.field3, ,......,  l.field21
from lake l
         join (
    select x.unnest, x.ordinality
    from unnest(array ['ticker1','ticker2', ....., 'ticker4299', 'ticker4300']) with ordinality
             as x (unnest, ordinality)) as r on l.ticker = r.unnest
where time = '2019-06-20'
order by r.ordinality;
```

**Comment by euri10** [comment] 2019-07-01 11:02
even this one takes 1.9s
```
    engine = create_engine(str(databaselake.url))
    c = engine.connect()
    psycopg0 = time.time()
    psycopg_result = c.execute(stmt).fetchall()
    psycopg1 = time.time()
    print(f"psycopg: {psycopg1-psycopg0}")
    c.close()
```

**Comment by tomchristie** [comment] 2019-07-02 11:09
I guess the first thing to do here would be to try to get some finer grain information about:

* Where the extra time is going there?
* If the auto-compiled statement really is exactly the same as the one you're manually compiling or not?
* How the compilation differs in the two cases (If it does).

As it currently stands there's not enough here for me to be able to replicate the issue, so you'd need to progress it on your side, or else try to reduce it to a small replicable example.

**Comment by euri10** [comment] 2019-07-03 21:48
sorry for the delay, it's fairly involved, I tried as much as possible to simplify things, here are the results, `core` 0.25s and `raw_core` 0.03s, they are the same.

most of the time for the test is spent inserting stuff, sorry for that but I need mass data so, it inserts 10k tickers for 30 dates.

The test is called [test_slow](https://github.com/euri10/databases/blob/9e4bcb4ac579dfd1ad0d34ca0a830e985888036e/tests/test_databases.py#L836) and it runs the same query twice after a big table is built.

the 1st query I called `core` is 
```
            core = (
                select(columns_asked)
                    .select_from(l.join(r, l.c.ticker == r.c.unnest))
                    .where(l.c.time == "2015-06-28")
                    .order_by(r.c.ordinality)
            )


            core0 = time.time()
            core_result = await database.fetch_all(core)
```

the second one I called raw_core is it's compiled version with bind literals

```
            raw_core = str(core.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True}))
            rawcore0 = time.time()
            rawcore_result = await database.fetch_all(raw_core)
```

I could have written it manually results are the same

the query time difference increases if this k increase:

`            rand_tickers = (f"ticker{r}" for r in random.choices(list(range(len(ticker_list))), k=2000))`

The query in a simplified pseudo code form would be:

```
select l.field3, l.field2, l.field4, l.field1
from lake l
         join (
    select x.unnest, x.ordinality
    from unnest(array ['ticker123','ticker221', K RANDOM TICKERS HERE TOTAL, ...  'ticker2']) with ordinality
             as x (unnest, ordinality)) as r on l.ticker = r.unnest
where time = '2019-06-28'
order by r.ordinality;
```
I pushed a [PR](https://github.com/encode/databases/pull/120) for discussion, it doesn't solve the issue, the test runs with these arguments (to get the logs)
The k number and the number of query are fairly large to demonstrate but of course can be changed should this be helpful to get why the massive discrepancy happens.

```
Launching pytest with arguments --log-cli-level=INFO -s test_databases.py::test_slow in /home/lotsos/PycharmProjects/databases/tests
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-5.0.0, py-1.8.0, pluggy-0.12.0
rootdir: /home/lotsos/PycharmProjects/databases
plugins: cov-2.7.1collected 1 item

test_databases.py::test_slow[postgresql:/postgres:postgres@localhost:5555/postgres] 

========================== 1 passed in 104.33 seconds ==========================

Process finished with exit code 0

-------------------------------- live log call ---------------------------------
INFO     test_databases:test_databases.py:879 core: 0.2540750503540039
INFO     test_databases:test_databases.py:885 rawcore: 0.03182554244995117
PASSED
```

**Comment by tomchristie** [comment] 2019-07-04 09:57
At the moment I'm closing this off in line with #120 

It *really* needs to be reduced right down to a simple, clearly identified, easily reproducible case. Right now it's unclear if the issue is something to do with the way you're using SQLAlchemy Core, or if there's legitimately an underlying issue with databases, and there's no real way for me to determine that without spending a vast amount of time trying to dig into what's been presented here.

Very happy to reopen, if this can be reduced to a clear, simple, reproducible example.

**Closed by tomchristie** 2019-07-04 09:57 UTC

**Comment by euri10** [comment] 2019-09-23 14:17
Hoping it is simple enough, it inserts 1100 notes, 100 have completed to False the rest has True and the text is random.
I build a query `core` selecting the false notes
 `raw_core` is the same query, compiled by sqlalchemy using the postgres dialect
I dont get why there is so much difference in time execution on a simple select.
on more complicated queries where databaes does the compilation of arguments, it's even worse, but I wanted to keep it simple as required,
maybe I'm totally of, in which case I'd loveto be enlightened on what I'm doing wrong.
 
```
POSTGRES_ONLY = [u for u in DATABASE_URLS if 'postgres' in u]

notes_len_data = [(10),(100),(1000),(10000), (100000)]
@pytest.mark.parametrize("notes_len", notes_len_data)
@pytest.mark.parametrize("database_url", POSTGRES_ONLY)
@async_adapter
async def test_another_slow(database_url,notes_len):
    async with Database(database_url) as database:
        async with database.transaction(force_rollback=True):
            # insert x notes
            query = notes.insert()
            valuestrue = [{"text": str(uuid.uuid4), "completed": True} for i in range(1000)]
            await database.execute_many(query, valuestrue)
            valuesfalse = [{"text": str(uuid.uuid4), "completed": False} for i in range(100)]
            await database.execute_many(query, valuesfalse)

            # 2 queries, one using core other using str compiled by sqlalchemy
            core = select(['*']).where(notes.c.completed == False)
            raw_core = str(core.compile(dialect=postgresql.dialect(),
                                        compile_kwargs={"literal_binds": True}))

            # calculating core time
            core0 = time.time()
            core_result = await database.fetch_all(core)
            core1 = time.time()
            logger.info(f"core: {core1 - core0}")

            # calculating raw core time
            rawcore0 = time.time()
            rawcore_result = await database.fetch_all(raw_core)
            rawcore1 = time.time()
            logger.info(f"rawcore: {rawcore1 - rawcore0}")

            # making sure both queries fetch the same
            for idx, _ in enumerate(core_result):
                assert core_result[idx]._row == rawcore_result[idx]._row

            # log diff
            logger.info(f'{(rawcore1 - rawcore0) / (core1 - core0):.2f}')
            assert rawcore1 - rawcore0 < core1 - core0
```

ran with `--log-cli-level=info`

```
-------------------------------- live log call ---------------------------------
test_databases.py          917 INFO     core: 0.006321430206298828
test_databases.py          923 INFO     rawcore: 0.0011773109436035156
test_databases.py          930 INFO     0.19
PASSED
test_databases.py::test_another_slow[postgresql:/postgres:postgres@localhost:5438/postgres-100] 
-------------------------------- live log call ---------------------------------
test_databases.py          917 INFO     core: 0.006414175033569336
test_databases.py          923 INFO     rawcore: 0.000995635986328125
test_databases.py          930 INFO     0.16
PASSED
test_databases.py::test_another_slow[postgresql:/postgres:postgres@localhost:5438/postgres-1000] 
-------------------------------- live log call ---------------------------------
test_databases.py          917 INFO     core: 0.010882377624511719
test_databases.py          923 INFO     rawcore: 0.0012750625610351562
test_databases.py          930 INFO     0.12
PASSED
test_databases.py::test_another_slow[postgresql:/postgres:postgres@localhost:5438/postgres-10000] 
-------------------------------- live log call ---------------------------------
test_databases.py          917 INFO     core: 0.006258249282836914
test_databases.py          923 INFO     rawcore: 0.0009894371032714844
test_databases.py          930 INFO     0.16
PASSED
test_databases.py::test_another_slow[postgresql:/postgres:postgres@localhost:5438/postgres-100000] 
-------------------------------- live log call ---------------------------------
test_databases.py          917 INFO     core: 0.006464242935180664
test_databases.py          923 INFO     rawcore: 0.0010251998901367188
test_databases.py          930 INFO     0.16
PASSED
test_databases.py::test_another_slow_reverse[postgresql:/postgres:postgres@localhost:5438/postgres-10] 
```

**Comment by tomchristie** [comment] 2019-09-30 10:57
I'm not sure - the thing to do here is try to isolate:

* What are statements being compile into when run using `databases`?
* How would you expect those to look if you were using the raw driver interface instead?

Presumably the issue is due to a difference between the *actual statements* being executed in each case.
